### ISSUE TITLE
why package.json in src/app/ ?

### ISSUE THREAD

**Issue by xmlking** [NathanWalker/nativescript-ng2-plugin-seed#12]
I noticed I am getting error when i remove package.json in src/app/
wonder when this file is needed!

**Comment by NathanWalker** [comment]
That file is critical to the demo app as it specifies the main file to run, without it has no idea which file to execute first:
https://github.com/NathanWalker/nativescript-ngx-plugin-seed/blob/master/src/app/package.json#L7
